#!/bin/sh

# This file is part of netfilter-persistent
# (was iptables-persistent)
# Copyright (C) 2009, Simon Richter <sjr@debian.org>
# Copyright (C) 2010, 2014 Jonathan Wiltshire <jmw@debian.org>
# Modified  (C) 2010-2020, Mario Rodriguez < colmena (at) bambusoft.com >
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

COLMENA_LOG="/var/log/colmena/colmena.log"
rc=0

load_rules()
{
	#load IPv6 rules
	if [ ! -f /etc/iptables/rules.v6 ]; then
		echo "Warning: skipping IPv6 (no rules to load)" 2> $COLMENA_LOG
	else
		/sbin/ip6tables-restore < /etc/iptables/rules.v6  2> $COLMENA_LOG
		if [ $? -ne 0 ]; then
			rc=1
		fi
	fi
}

save_rules()
{
	#save IPv6 rules
	#need at least ip6table_filter loaded:
	/sbin/modprobe -q ip6table_filter || true
	if [ ! -f /proc/net/ip6_tables_names ]; then
		log_action_cont_msg "Warning: skipping IPv6 (no modules loaded)"
	elif [ -x /sbin/ip6tables-save ]; then
		touch /etc/iptables/rules.v6
		chmod 0640 /etc/iptables/rules.v6
		/sbin/ip6tables-save > /etc/iptables/rules.v6 2> $COLMENA_LOG
		if [ $? -ne 0 ]; then
			rc=1
		fi
	fi
}

flush_rules()
{
	if [ ! -f /proc/net/ip6_tables_names ]; then
		echo "Warning: skipping IPv6 (no module loaded)"
	elif [ -x /sbin/ip6tables ]; then
		for chain in INPUT FORWARD OUTPUT
		do
			/sbin/ip6tables -P $chain ACCEPT 2> $COLMENA_LOG
		done
		for param in F Z X; do /sbin/ip6tables -$param; done
		for table in $(cat /proc/net/ip6_tables_names)
		do
			/sbin/ip6tables -t $table -F 2> $COLMENA_LOG
			/sbin/ip6tables -t $table -Z 2> $COLMENA_LOG
			/sbin/ip6tables -t $table -X 2> $COLMENA_LOG
		done
	fi
}

case "$1" in
start|force-start|restart|reload|force-reload)
	load_rules
	;;
save)
	save_rules
	;;
stop)
	# Why? because if stop is used, the firewall gets flushed for a variable
	# amount of time during package upgrades, leaving the machine vulnerable
	# It's also not always desirable to flush during purge
	echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
	;;
flush)
	flush_rules
	;;
status)
	rules=$(/sbin/ip6tables -n -L | wc -l)
	echo "ip6tables has ($rules) rules"
	;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit $rc
