#!/bin/sh

# This file is part of colmena
# Copyright (C) 2010-2020 Mario Rodriguez <colmena (at) bambusoft.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 3
# of the License.

set -e

COLMENA_LOG="/var/log/colmena/colmena.log"
rc=0

if [ $? -ne 0 ]; then
	rc=1
fi


case "$1" in
start|restart|reload|force-reload|force-start)
	running=$(ps -ef | grep knockd | egrep -v color)
	if [ -n "$running" ] ; then
		/etc/init.d/knockd stop
		sleep 3
	fi
	/etc/init.d/knockd start
	;;
save)
	;;
stop)
	/etc/init.d/knockd stop
	;;
flush)
	;;
status)
	echo "Showing colmena sequence port manager status..."
	/etc/init.d/knockd status | grep Active
	;;
*)
    echo "Usage: $0 {start|status|stop}" >&2
    exit 1
    ;;
esac

exit $rc
