-- MySQL Script generated by MySQL Workbench
-- Sat Oct 10 19:57:34 2020
-- Model: Colmena    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colmena
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `colmena` ;

-- -----------------------------------------------------
-- Schema colmena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colmena` DEFAULT CHARACTER SET utf8 ;
USE `colmena` ;

-- -----------------------------------------------------
-- Table `colmena`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`provider` ;

CREATE TABLE IF NOT EXISTS `colmena`.`provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NULL,
  `suportUrl` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`owner` ;

CREATE TABLE IF NOT EXISTS `colmena`.`owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `client_fk` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`server` ;

CREATE TABLE IF NOT EXISTS `colmena`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hostname` VARCHAR(15) NULL,
  `fqdn` VARCHAR(255) NULL,
  `ip4` VARCHAR(15) NOT NULL,
  `ip6` VARCHAR(39) NOT NULL,
  `vpn4` VARCHAR(15) NOT NULL,
  `vpn6` VARCHAR(39) NOT NULL,
  `os` VARCHAR(10) NULL,
  `cpus` TINYINT(1) NULL,
  `memory_mb` INT(11) NULL,
  `swap_mb` INT(11) NULL,
  `hdd1_mb` INT(11) NULL,
  `hdd2_mb` INT(11) NULL,
  `transfer_mb` INT(11) NULL,
  `location` VARCHAR(45) NULL,
  `provider` INT NOT NULL,
  `owner` INT NOT NULL,
  `active` TINYINT(1) NULL,
  `hive_hierarchy` ENUM('R', 'Q', 'B', 'L') NULL COMMENT 'R=Royal, Q=Queen, B=Bee, L=Larva',
  `hive_peer` TINYINT(1) NULL,
  `hive_port` INT NULL,
  `privateKey` VARCHAR(255) NULL,
  `publicKey` VARCHAR(255) NULL,
  `sharedSecret` VARCHAR(255) NULL,
  `lastContact` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_server_provider_idx` (`provider` ASC) VISIBLE,
  INDEX `fk_server_owner_idx` (`owner` ASC) VISIBLE,
  UNIQUE INDEX `hostname_idx` (`hostname` ASC) INVISIBLE,
  UNIQUE INDEX `fqdn_idx` (`fqdn` ASC) INVISIBLE,
  UNIQUE INDEX `ip4_idx` (`ip4` ASC) INVISIBLE,
  UNIQUE INDEX `ip6_idx` (`ip6` ASC) VISIBLE,
  UNIQUE INDEX `vpn4_idx` (`vpn4` ASC) INVISIBLE,
  UNIQUE INDEX `vpn6_idx` (`vpn6` ASC) VISIBLE,
  CONSTRAINT `fk_server_provider`
    FOREIGN KEY (`provider`)
    REFERENCES `colmena`.`provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_server_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `colmena`.`owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`ip_fw_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`ip_fw_list` ;

CREATE TABLE IF NOT EXISTS `colmena`.`ip_fw_list` (
  `ip` VARCHAR(39) NOT NULL,
  `cidr` VARCHAR(5) NULL,
  `list` ENUM('BL', 'GL', 'WL', 'UK') NOT NULL DEFAULT 'UK' COMMENT 'Black, Gray, White, Unknown',
  `last` ENUM('BL', 'GL', 'WL', 'UK') NULL DEFAULT 'UK',
  `blackListed` INT UNSIGNED NOT NULL DEFAULT 0,
  `greyListed` INT UNSIGNED NOT NULL DEFAULT 0,
  `whiteListed` INT UNSIGNED NOT NULL DEFAULT 0,
  `events` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `firstActivityDate` INT(11) NULL,
  `lastActivityDate` INT(11) NULL,
  `hostname` TEXT NULL,
  `blockDays` SMALLINT(6) UNSIGNED NULL,
  `propagated` TINYINT(1) NOT NULL DEFAULT 0,
  `listBlocked` TINYINT(1) NOT NULL DEFAULT 0,
  `src_ip` VARCHAR(39) NULL,
  `origin_ip` VARCHAR(39) NULL,
  PRIMARY KEY (`ip`),
  INDEX `ip_list_idx` (`ip` ASC, `list` ASC) INVISIBLE,
  INDEX `fad_idx` (`firstActivityDate` ASC) INVISIBLE,
  INDEX `lad_idx` (`lastActivityDate` ASC) INVISIBLE,
  INDEX `src_ip_idx` (`src_ip` ASC) INVISIBLE,
  INDEX `ori_ip_idx` (`origin_ip` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`port` ;

CREATE TABLE IF NOT EXISTS `colmena`.`port` (
  `id` INT NOT NULL,
  `IANA_assignment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`server_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`server_port` ;

CREATE TABLE IF NOT EXISTS `colmena`.`server_port` (
  `server` INT NOT NULL,
  `port` INT NOT NULL,
  `lastUpdate` INT(11) NULL,
  `events` BIGINT UNSIGNED NULL,
  INDEX `fk_server-port_server_idx` (`server` ASC) VISIBLE,
  INDEX `fk_server-port_port_idx` (`port` ASC) VISIBLE,
  UNIQUE INDEX `srv_port_idx` (`server` ASC, `port` ASC) VISIBLE,
  CONSTRAINT `fk_server-port_server`
    FOREIGN KEY (`server`)
    REFERENCES `colmena`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_server-port_port`
    FOREIGN KEY (`port`)
    REFERENCES `colmena`.`port` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`ip_port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`ip_port` ;

CREATE TABLE IF NOT EXISTS `colmena`.`ip_port` (
  `ip` VARCHAR(39) NOT NULL,
  `port` INT NOT NULL,
  `lastUpdate` INT(11) NULL,
  `events` BIGINT UNSIGNED NULL,
  INDEX `fk_ip_port_port_idx` (`port` ASC) VISIBLE,
  INDEX `fk_ip_port_ip_fw_list_idx` (`ip` ASC) VISIBLE,
  UNIQUE INDEX `ip_port_idx` (`ip` ASC, `port` ASC) VISIBLE,
  CONSTRAINT `fk_ip_port_port`
    FOREIGN KEY (`port`)
    REFERENCES `colmena`.`port` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip_port_ip_fw_list`
    FOREIGN KEY (`ip`)
    REFERENCES `colmena`.`ip_fw_list` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`trigger_script`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`trigger_script` ;

CREATE TABLE IF NOT EXISTS `colmena`.`trigger_script` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `default_port` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colmena`.`ip_trigger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colmena`.`ip_trigger` ;

CREATE TABLE IF NOT EXISTS `colmena`.`ip_trigger` (
  `ip` VARCHAR(39) NOT NULL,
  `trigger_id` INT NOT NULL,
  `lastUpdate` INT(11) NULL,
  `events` BIGINT UNSIGNED NULL,
  INDEX `fk_ip-trigger_ip_fw_list_idx` (`ip` ASC) VISIBLE,
  INDEX `fk_ip-trigger_trigger_idx` (`trigger_id` ASC) VISIBLE,
  UNIQUE INDEX `ip_trig_idx` (`ip` ASC, `trigger_id` ASC) VISIBLE,
  CONSTRAINT `fk_ip-trigger_ip_fw_list`
    FOREIGN KEY (`ip`)
    REFERENCES `colmena`.`ip_fw_list` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ip-trigger_trigger`
    FOREIGN KEY (`trigger_id`)
    REFERENCES `colmena`.`trigger_script` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
